### ISSUE TITLE
Midtake Improvements

### ISSUE THREAD

**Issue by CalebONeal07** [koibots8230/Newbie-Cuttlefish#3]
@GrantS-R Now that you've finished a basic Midtake subsystem go ahead and read [this](https://www.chiefdelphi.com/t/clear-concise-best-practices-for-sparkmax-neo-current-limiting/405541) thread and figure out what changes you need to make based on it. 

Hint: Midtake uses a [Neo 550](https://www.revrobotics.com/rev-21-1651/)

**Comment by GrantS-R** [comment]
Implemented the changes, the Neo SHOULD stop when current is over 20.
